arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]

c_compiler_version:
  - 12          # [linux and aarch64]
  - 12          # [linux and ppc64le]
  - 12          # [linux and x86_64]
  - 10          # [linux and aarch64]
  - 10          # [linux and ppc64le]
  - 10          # [linux and x86_64]

cxx_compiler_version:
  - 12          # [linux and aarch64]
  - 12          # [linux and ppc64le]
  - 12          # [linux and x86_64]
  - 10          # [linux and aarch64]
  - 10          # [linux and ppc64le]
  - 10          # [linux and x86_64]

fortran_compiler_version:
  - 10          # [linux and aarch64]
  - 10          # [linux and ppc64le]
  - 10          # [linux and x86_64]
  - 10          # [linux and aarch64]
  - 10          # [linux and ppc64le]
  - 10          # [linux and x86_64]

cuda_compiler_version:
  - 12.0        # [linux and aarch64]
  - 12.0        # [linux and ppc64le]
  - 12.0        # [linux and x86_64]
  - 12.0        # [win]
  - 11.2        # [linux and aarch64]
  - 11.2        # [linux and ppc64le]
  - 11.2        # [linux and x86_64]
  - 11.2        # [win]

cuda_compiler:
  - nvcc

cudnn:
  - undefined   # [linux and aarch64]
  - undefined   # [linux and ppc64le]
  - undefined   # [linux and x86_64]
  - undefined   # [win]
  - undefined   # [linux and aarch64]
  - undefined   # [linux and ppc64le]
  - undefined   # [linux and x86_64]
  - undefined   # [win]

cdt_name:
  - cos7        # [linux and aarch64]
  - cos7        # [linux and ppc64le]
  - cos7        # [linux and x86_64]
  - cos7        # [linux and aarch64]
  - cos7        # [linux and ppc64le]
  - cos7        # [linux and x86_64]

docker_image:
  - quay.io/condaforge/linux-anvil-aarch64            # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-ppc64le            # [linux and ppc64le]
  - quay.io/condaforge/linux-anvil-cos7-x86_64        # [linux and x86_64]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.2  # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2  # [linux and ppc64le]
  - quay.io/condaforge/linux-anvil-cuda:11.2          # [linux and x86_64]
